### ISSUE TITLE
BUG Linux 下无法运行程序

### ISSUE THREAD

**Issue by juruo888** [class-tools/Learning-Focus#1]
Description: 在 Linux 系统下，运行程序报错。

Screenshot:

![image](https://user-images.githubusercontent.com/106530969/182337243-b85a2395-2281-4710-9ac2-8236409a4b69.png)

Program Version: `1.0.0-alpha.1`

Operating System Version: `NOI Linux 2.0 (Ubuntu 20.04 LTS)`

**Comment by ren-yc** [comment]
在初版 https://github.com/class-tools/Learning-Focus/commit/93605021cccce7f1c82993a3a38b7b1b7ab66256 中，我们已在 Linux 平台下测试，均无问题。

请您检查您的摄像头及视频流。

**Comment by ren-yc** [comment]
附注：无异常测试版本为 Ubuntu 16.04。（虽可能与操作系统版本无关）

**Comment by ren-yc** [comment]
关于虚拟机配置摄像头的问题，参见 https://blog.csdn.net/qq_37429313/article/details/116202732 。

**Comment by ren-yc** [comment]
关于虚拟机配置摄像头的问题，参见 https://blog.csdn.net/qq_37429313/article/details/116202732 。
