### ISSUE TITLE
BUG Linux 下程序运行异常

### ISSUE THREAD

**Issue by juruo888** [class-tools/Learning-Focus#2]
Description: 

- [x] 按下 ESC 程序退出后控制台报错。
- [x] `recent.json` 无内容。
- [x] Matplotlib 窗口没有出现。

Screenshot:

![image](https://user-images.githubusercontent.com/106530969/182518751-48fa40c4-8d95-4708-ae9f-433dd8732e5c.png)

![image](https://user-images.githubusercontent.com/106530969/182518736-3a2e2455-5a21-492d-bb9a-cb15b00b5191.png)

![image](https://user-images.githubusercontent.com/106530969/182534307-6506d075-120f-4017-86db-f8f196c623c4.png)

Program Version: `1.0.0-alpha.1`

Operating System Version: `NOI Linux 2.0 (Ubuntu 20.04 LTS)`

**Comment by ren-yc** [comment]
OpenCV 的视频实时显示窗口确实没有图标，有图标的是 Matplotlib 的双柱状图显示窗口。
