### ISSUE TITLE
BUG README 图炸了

### ISSUE THREAD

**Issue by juruo888** [class-tools/Learning-Focus#4]
Description: 项目 Logo 图片出现问题。

Screenshot:

![image](https://user-images.githubusercontent.com/106530969/188838471-c4630bbc-8170-40f4-a020-184ef3c13f5a.png)

Program Version: `1.0.0-beta.1`

Operating System Version: `Windows 10`

**Comment by ren-yc** [comment]
~~没有点耐心啊？本地早就改好了，就仅仅这个更改不足以 Commit。~~
